[[constraint]]
  name = "github.com/containernetworking/plugins"
  revision = "fe60fcddb897079746ec1523fd1837ab05b1e689"

[[constraint]]
  name = "github.com/go-ini/ini"
  revision = "20b96f641a5ea98f2f8619ff4f3e061cff4833bd"

[[constraint]]
  name = "github.com/cri-o/cri-o"
  revision = "485227d727401fa0472a449b5df3b0537e314ebb"

[[override]]
  name = "github.com/cri-o/ocicni"
  revision = "8a4ca077a093fc24475fe296b9eb063ec1a279a5"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "d0303fe809921458f417bcf828397a65db30a7e4"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "f4982d86f7fde0b6f953cc62ccc4022c519a10a9"

[[override]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "a1b50f621a48ad13f8f696a162f684a241307db0"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "890a5c3458b43e6104ff5da8dfa139d013d77544"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "ac249472b7de27a9e8990819566d9be95ab5b816"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  revision = "c2a3de3b38bd00f07290c3c5e12b4dbc04ec8666"

[[constraint]]
  name = "github.com/vishvananda/netns"
  revision = "86bef332bfc3b59b7624a600bd53009ce91a9829"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "04f50cda93cbb67f2afa353c52f342100e80e625"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "v1.4.2"

[[constraint]]
  name = "github.com/intel/govmm"
  revision = "b3e7a9e78463a10f2a19e1a966c76a3afb215781"

[[constraint]]
  name = "github.com/kata-containers/agent"
  revision = "2948e1a3c4b03268e4526dbd8576fc5cb8336533"

[[constraint]]
  name = "github.com/containerd/cri-containerd"
  revision = "4dd6735020f5596dd41738f8c4f5cb07fa804c5e"

[[constraint]]
  name = "github.com/safchain/ethtool"
  revision = "79559b488d8848b53a8e34c330140c3fc37ee246"

[[constraint]]
 name = "github.com/containerd/containerd"
 revision = "f05672357f56f26751a521175c5a96fc21fa8603"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "4cbf7e384e768b4e01799441fdf2a706a5635ae7"

[[override]]
  branch = "master"
  name = "github.com/hashicorp/yamux"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  revision = "5017d4e9a9cf2d4381db99eacd9baf84b95bfb14"
  name = "github.com/containerd/cgroups"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/procfs"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v12.0.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  revision = "e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "k8s.io/utils"
  revision = "6999998975a717e7f5fc2a7476497044cb111854"
